version: '3.8'

services:
  ai-engine:
    build: .
    container_name: ai-engine
    ports:
      - "8080:8080"
    environment:
      # Application
      APP_VERSION: "1.0.0"
      ENVIRONMENT: "development"
      PORT: 8080
      LOG_LEVEL: "DEBUG"
      
      # Authentication (generate with: openssl rand -base64 32)
      INTERNAL_JWT_SECRET: "your-dev-jwt-secret-min-32-characters-change-in-production"
      
      # AI Model Keys (use development keys)
      PRIMARY_MODEL_KEY: "dev-primary-key"
      SECONDARY_MODEL_KEY: "dev-secondary-key"
      
      # Provider Configuration
      PRIMARY_PROVIDER: "INLEGALBERT"
      FALLBACK_PROVIDERS: "DeepSeek,Grok"
      
      # Vector Store
      VECTOR_STORE_URL: "http://localhost:6333"
      
      # Request Constraints
      REQUEST_TIMEOUT_SECONDS: 30
      MAX_PAYLOAD_SIZE_BYTES: 5242880
      CONCURRENCY_LIMIT_PER_WORKER: 10
      
      # Rate Limiting
      RATE_LIMIT_PER_MINUTE: 1000
      DAILY_QUOTA_LIMIT: 100000
      
      # Smoke Tests
      RUN_SMOKE_TESTS_ON_DEPLOY: "false"
      FAIL_DEPLOY_ON_SMOKE_TEST_FAILURE: "false"
    volumes:
      - ./:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Local vector database for development
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   container_name: qdrant
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - qdrant_storage:/qdrant/storage

# volumes:
#   qdrant_storage:

